services:
  app:
    image: todo-front-dev-1
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile #./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-front-dev-1
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-1
    depends_on:
      - app # wait for the frontend container to be started
