services:
  app:
    image: todo-front-dev-1
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile #./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    #ports:
    #  - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    container_name: todo-front-dev-1
  server:
    image: todo-back-dev-1
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
      args:
        - DOCKER_ENV = TRUE
    volumes:
      - ./todo-backend/:/usr/src/app
    #ports:
    #  - 3001:3001
    environment:
      - REDIS_URL = redis://redis:6379
      - MONGO_URL = mongodb://the_username:the_password@mongo:27017/the_database
      - DOCKER_ENV = TRUE
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-2
    depends_on:
      - app # wait for the frontend container to be started
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    ports:
      - 6379:6379
    image: redis:7.0.12
    command: redis-server --appendonly yes --save 20 1 --loglevel warning --requirepass jotain
    volumes:
      - ./todo-backend/redis_data:/data

volumes:
  mongo_data:
